allow_remote_control yes
foreground            #D9D9D9
background            #1E2227
cursor                #D9D9D9
cursor_text_color     #1E2227
selection_foreground  none
selection_background  #5C8EC7
color0  #1E2227
color8  #30343C
color1  #E07093
color9  #DFB4C9
color2  #8BBE67
color10 #B1C6AC
color3  #BB8E67
color11 #C3B470
color4  #304A68
color12 #5C8EC7
color5  #8B5FC7
color13 #B1A3DF
color6  #5CBE97
color14 #A0C4BD
color7  #D9D9D9
color15 #FFFFFF

